### ISSUE TITLE
Sort by country label

### ISSUE THREAD

**Issue by pvledoux** [johndwells/craft.territories#4]
Hi John, do you know how I could sort my entries by country label. Currently, using `.order('adrCountry asc')` is sorting by iso code.

**Comment by johndwells** [comment]
Hey @pvledoux,

Hmm that's a tough one, since of  course it's the ISO codes which are being saved to the DB.  Off the top of my head you could take a look at using the Preparse Field (https://github.com/aelvan/Preparse-Field-Craft) to save the country name in a field which you could then sort by. The only caveat is that, unless I'm mistaken, you'll have to re-save any existing entries you have (as in it won't retro-actively insert values into the db for each entry field).

Hope that helps!
John

**Comment by pvledoux** [comment]
Thanks for your response. In fact I just finished to hack my template with a very ugly code. I hardcoded an array of iso code in the correct order, I then make one query per code, get only entry ids, then re-query based on those ids, with fixedOrder(true). Yeah...well... I have to cache everything, but that do the trick for now ;)
